### PR TITLE
replacing tf.image.combined_non_max_suppression with tf.image.non_max_suppression_with_scores

### PR DESCRIPTION
**Pull request by rajan780**
I replaced combined_nms with nms_with_scores to enable softnms as well as some frameworks not support combined_nms api so it is difficult to port from one framework to another.

### CODE REVIEW

**Comment by rajan780** [comment]
Hi @zzh8829 
Please review the above changes. These changes are related to non max suppression. Actually in code we are using tf.image.combined_non_max_suppression but this api is not supported by onnx. so we used tf.image.non_max_suppression_with_scores and it is working. For more details please refer https://github.com/onnx/tensorflow-onnx/issues/847#issuecomment-779230399

**Comment by andreselizondo-adestech** [comment]
Just tested this.
I can confirm it works on `tflite_runtime`, not just `tf.lite`

**Comment by rajan780** [comment]
> Just tested this.
> I can confirm it works on `tflite_runtime`, not just `tf.lite`
> 
> Only necessary change was to set `batch_size=1` for YoloV3 input:
> `x = inputs = Input([size, size, channels], batch_size=batch_size, name='input')`
> 
> This is to avoid the issue with:
> `RuntimeError: tensorflow/lite/kernels/reshape.cc:58 stretch_dim != -1 (0 != -1)Node number 343 (RESHAPE) failed to prepare.`

Thanks @andreselizondo-adestech to confirm. yes, i am also adding batch_size

**Comment by zzh8829** [comment]
just got some time to test this today seems good!

**Comment by zzh8829** [comment]
just got some time to test this today seems good!

**Pull request merged**
