### PR TITLE
Fix tflite export

### PR DESCRIPTION
**Pull request by ZwAnto**
Hi,

I was looking into converting model using tflite converter and stumble on two issues:
 * tf.image.combined_non_max_suppression not supported by tflite
 * tf.size not supported by tflite (used in tf.meshgrid function)

For tf.image.combined_non_max_suppression I found a fix here:
https://stackoverflow.com/questions/64490203/tf-lite-non-max-suppression

For tf.size I simply reimplement a meshgrid function that suit our needs.

I made some test and got identical results using tools/export_tflite.py and detect.py on data/girl.png using tiny darknet.

### CODE REVIEW

**Comment by ZwAnto** [comment]
It may solve issues #200 and #205

**Comment by andreselizondo-adestech** [comment]
Just tested this, works like a charm.
Keep in mind, you need to feed the correct parameters to the `export_tflite.py` script.

**Comment by andreselizondo-adestech** [comment]
@ZwAnto For some reason, I'm unable to generate a pull request to your repository.
I fixed an issue and also added a script to run inference on TFLite.
Check it out at https://github.com/andreselizondo-adestech/yolov3-tf2

**Comment by zzh8829** [comment]
just got some time to test this today seems good!

**Comment by berserkr** [comment]
Do you guys know how to interpret the results coming out of tflite? I am not sure how to interpret it. Thank you!

**Pull request merged**
